os: osx
osx_image: xcode10.2

language: bash

git:
  depth: false
  
before_cache:
  - brew cleanup
  
cache:
  - directories:
    - $HOME/Library/Caches/Homebrew
     
before_install:
  - whoami
  - echo "Start of pipeline"
  - HOMEBREW_NO_AUTO_UPDATE=1
 
cache:
  - directories:
    - $HOMEBREW_NO_AUTO_UPDATE=1
   
script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
  
notifications:
  email:
    recipients:
      - rajputrao@gmail.com
      - s329940@oslomet.no
    on_success: never # default: change
    on_failure: always # default: always 
    
after_script:
  - echo "End of Pipeline"
